export const SalaryAdditionalInput = [
    {
        id: 1,
        labelID : 'exampleInput6',
        labelTitle: 'Special Pay',     
        inputID: 'exampleInput6',
        formControlName: 'speacialPay',
    },
    {
        id: 2,
        labelID : 'exampleInput7',
        labelTitle: 'Arrear Pay',
        inputID: 'exampleInput7',
        formControlName: 'arrearPay',
    },
    {
        id: 3,
        labelID : 'exampleInput8',
        labelTitle: 'Dearness Allowance',
        inputID: 'exampleInput8',
        formControlName: 'dearnessAllowance',
    },
    {
        id: 4,
        labelID : 'exampleInput9',
        labelTitle: 'Allowance for Support Staff',
        inputID: 'exampleInput9',
        formControlName: 'supportStaffAllowance',
    },
    {
        id: 5,
        labelID : 'exampleInput10',
        labelTitle: 'Leave Allowance',
        inputID: 'exampleInput10',
        formControlName: 'leaveAllowance',
    },
    {
        id: 6,
        labelID : 'exampleInput11',
        labelTitle: 'Honorarium/Reward/Fee',
        inputID: 'exampleInput11',
        formControlName: 'honorariumRewardFee',
    },
    {
        id: 7,
        labelID : 'exampleInput12',
        labelTitle: 'Overtime Allowance',
        inputID: 'exampleInput12',
        formControlName: 'overtimeAllowance',
    },
    {
        id: 8,
        labelID : 'exampleInput13',
        labelTitle: 'Bonus/Ex-gratia',
        inputID: 'exampleInput13',
        formControlName: 'bonusExGratia',
    },
    {
        id: 9,
        labelID : 'exampleInput14',
        labelTitle: 'Other Allowances',
        inputID: 'exampleInput14',
        formControlName: 'otherAllowance',
    },
    {
        id: 10,
        labelID : 'exampleInput15',
        labelTitle: 'Employer’s Contribution to a RPF',
        inputID: 'exampleInput15',
        formControlName: 'empContributionToRPF',
    },
    {
        id: 11,
        labelID : 'exampleInput16',
        labelTitle: 'Interest Accrued on a RPF',
        inputID: 'exampleInput16',
        formControlName: 'interestAccruedOnRPF',
    },
    {
        id: 12,
        labelID : 'exampleInput17',
        labelTitle: 'Deemed Income for Transport Facility',
        inputID: 'exampleInput17',
        formControlName: 'deemedIncomeForTranfortFacility',
    },
    {
        id: 13,
        labelID : 'exampleInput18',
        labelTitle: 'Deemed Income for Free Furnished/Unfurnished Accommodation',
        inputID: 'exampleInput18',
        formControlName: 'deemedIncomeForFreeFurnishedNonFurnishedAcco',
    },
    {
        id: 14,
        labelID : 'exampleInput19',
        labelTitle: 'Other, If Any (Give Detail)',
        inputID: 'exampleInput19',
        formControlName: 'otherIfAny',
    },

]